FROM apache/spark:4.1.0-preview3-scala2.13-java21-python3-ubuntu

USER root

WORKDIR /app

COPY . /app

RUN mkdir -p /opt/ivy-cache && chown -R spark:spark /opt/ivy-cache && \
    python3 -m pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir fastapi uvicorn pyspark

ENV PYTHONPATH=/app

USER spark

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

